name: 'publish'

# run on any push
on:
  release:
    types:
    - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v3
    - name: Set up Node.js with the NPM registry
      uses: actions/setup-node@v2
      with:
        registry-url: 'https://registry.npmjs.org'
    - name: Install dependencies
      run: npm ci
    - name: Build the package
      run: npm run build
    - name: Publish to NPM
      run: npm publish
      env:
        # setup-node ensures that the following env variable will be used for auth:
        # https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
